env:
  browser: true
  es6: true
  amd: true
  node: true
  mocha: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: 'off'
  require-jsdoc:
    - error
    - require:
          FunctionDeclaration: true
          MethodDefinition: true
          ClassDeclaration: true
          ArrowFunctionExpression: false
          FunctionExpression: false

settings:
  react:
    version: '16.5.2'
