const NOTIFICATIONS_ENABLED = 'NOTIFICATIONS_ENABLED'
const LOGGING_ENABLED = 'LOGGING_ENABLED'
const PROFILE_FIRSTNAME = 'PROFILE_FN'
const PROFILE_LASTNAME = 'PROFILE_LN'
const PROFILE_BIRTHDAY = 'PROFILE_BD'
const SYNC_ADAPTER = 'SYNC_ADAPTER'
const SYNC_PERFORMED = 'SYNC_PERFORMED'
const WEBDAV_HTTPS = 'WEBDAV_HTTPS'
const WEBDAV_URL = 'WEBDAV_URL'
const WEBDAV_USERNAME = 'WEBDAV_USERNAME'
const WEBDAV_PASSWORD = 'WEBDAV_PASSWORD'

export default {
  NOTIFICATIONS_ENABLED,
  LOGGING_ENABLED,
  PROFILE_FIRSTNAME,
  PROFILE_LASTNAME,
  PROFILE_BIRTHDAY,
  SYNC_ADAPTER,
  SYNC_PERFORMED,
  WEBDAV_HTTPS,
  WEBDAV_URL,
  WEBDAV_USERNAME,
  WEBDAV_PASSWORD
}
